apiVersion: apps/v1
kind: Deployment
metadata:
  name: walb2-app-deployment
  namespace: walb2-app
  labels:
    app: walb2-app
spec:
  replicas: 3  # 고가용성을 위해 3개 복제본 실행
  selector:
    matchLabels:
      app: walb2-app
  template:
    metadata:
      labels:
        app: walb2-app
    spec:
      containers:
      - name: walb2-app
        image: ${ECR_REGISTRY}/walb2-app-ecr:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/music
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/music
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: walb2-app-service
  namespace: walb2-app
  labels:
    app: walb2-app
spec:
  type: ClusterIP
  selector:
    app: walb2-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http 